### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Shalopay** [Shalopay/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ShalopayShadow** [comment]
I'm just an ordinary person known as the president of the Chinese Basketball Association (CBA), president and owner of the CBA’s Shanghai Sharks, Founder & Proprietor of Yao Family Wines Company. In past, I was the NBA player, the tallest player in Association (what irony the tallest person in Association from a country known for its low stature people, ha-ha). 
As a basketball player and functionary want to help contribute to the growth and development of basketball in China, at the youth, professional and national team levels.
As an environmentalist, with collaboration with WildAid, hope to eliminate the illegal ivory trade and reduce the consumption of traditional Chinese shark fin soup.
And as winemaker I want to produce the best wine across the world!

**Comment by Shalopay** [comment]
you are the best!!!
