### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Shalopay** [Shalopay/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ShalopayShadow** [comment]
https://www.instagram.com/yao
https://www.facebook.com/Yao
https://en.wikipedia.org/wiki/Yao_Ming
https://www.britannica.com/biography/Yao-Ming
https://www.basketball-reference.com/players/m/mingya01.html

**Comment by Shalopay** [comment]
nice work!
