### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Shalopay** [Shalopay/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ShalopayShadow** [comment]
Awards
8× NBA All-Star (2003–2009, 2011)
2× All-NBA Second Team (2007, 2009)
3× All-NBA Third Team (2004, 2006, 2008)
NBA All-Rookie First Team (2003)
No. 11 retired by Houston Rockets
CBA MVP (2001)
CBA champion (2002)
CBA Finals MVP (2001)
3× CBA rebounding leader (2000, 2001, 2002)
3× CBA blocks leader (2000, 2001, 2002)
2× CBA Slam Dunk leader (2000, 2001)
3× FIBA Asia Cup MVP (2001, 2003, 2005) 

Statisics
Points	9,247 (19.0 ppg)
Rebounds	4,494 (9.2 rpg)
Blocks	920 (1.9 bpg) 

Some funny stuff
Yao Ming Face is a Rage Comics (that became a widely used Internet meme) character used to imply carelessness or giving up. The meme originated at a press conference in 2009 when professional basketball player Yao Ming made the face. There are alternate counterparts – a scared version of the face was also made which is used to imply fear; there also is another counterpart of it that has his lips tucked in saying "PFFT", as he was preparing to laugh.

**Comment by Shalopay** [comment]
hmmm, thats pretty interesting
